services:
  app:
    build: 
      context: .
    develop:
      watch:
        - action: sync+restart
          target: /docker-entrypoint.sh
          path: docker-entrypoint.sh
    env_file: ./.env
    volumes:
      - ./repo:/data
      - ./config.json:/composer/config.json
    ports:
      - "8000:8000"
      - "3000:3000"
    secrets:
      - id_ed25519
secrets:
  id_ed25519:
    file: ~/.ssh/id_ed25519

  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword