services:
  app:
    build: 
      context: .
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./repo:/data
      - ./config.json:/composer/config.json
    ports:
      - "80:8000"
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword